services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME:${MONGO_DB_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD:${MONGO_DB_ROOT_PW}
    ports:
      - 27017:27017
    volumes:
      - mongo_data_container:/data/db

volumes:
  mongo_data_container:
